#!/bin/sh

# Make sure LibreOffice is not running
killall soffice.bin

# Start LibreOffice Writer, then wait
lowriter &
wait

# Echo once the script is finished
echo "You closed Writer, let's run it again, but use 'wait' on the same line using: '; wait'"

# Start LibreOffice Writer again
lowriter; wait

# Echo the final message
echo "Finally, we're done."
