#!/bin/sh

# Start LibreOffice Writer with '&' so the terminal returns to the prompt
lowriter

# Echo to show the script has moved on
echo "You didn't see this message until closing the Writer window in the GUI."
