#!/bin/sh

read -p "Enter something
" checkTHIS

# This variable needs "quotes" in case the value has a space so it doesn't break the test
while [ -z "${checkTHIS}" ]

do

echo "You must comply. Resistance is futile."
read -p "Enter something
" checkTHIS

done


echo ${checkTHIS}

