#!/bin/sh

myChoice=$1

case $myChoice in

1)
echo "You chose a number. It is: one ($myChoice)"
;;

2)
echo "You chose a number. It is: two ($myChoice)"
;;

3)
echo "You chose a number. It is: three ($myChoice)"
;;


a)
echo "You chose a letter. It is: A ($myChoice)"
;;


b)
echo "You chose a letter. It is: B ($myChoice)"
;;


c)
echo "You chose a letter. It is: C ($myChoice)"
;;

esac

