#!/bin/sh

read -p "Enter a number to count to
" countTo

# 1 while
while [ -z ${countTo} ]

do

echo "You must comply. Resistance is futile."
read -p "Enter a number to count to
" countTo

done

# Talk back
echo "'ight, counting to ${countTo}..."
sleep 1

# Start a counter
thisCount=0

# 2 while
while [ ${thisCount} -le ${countTo} ]

do

# echo the count
echo ${thisCount}

# wait one second
sleep 1

# add 1
thisCount=$(expr ${thisCount} + 1)

done
