#!/bin/sh

# Start a counter
thisCount=0

while [ ${thisCount} != 15 ]

do

# echo the count
echo ${thisCount}

# wait one second
sleep 1

# add 1, "increment" (learn more in Lesson 9)
thisCount=`expr ${thisCount} + 1`

done
