#!/bin/sh

# To make custom error messages, we need this, not "set -e"
set -o errexit

# Log "exit 0" output in "exit-0.log"
exec 0>> exit-0.log

# Create a message upon "exit 0" ( 0> )
echo "Hey there! I'm exiting ZERO because I'm strange and have nothing to do with my time!" >&0

# Exit code 0 ( 0> )
exit 0
