#!/bin/sh

# Log all normal STDOUT output in "normal.log"
exec 1>> normal.log

# Log all STDERR error messages in "error.log"
exec 2>> error.log

# Run ls: success to STDOUT
ls

# Run ls for a dir that doesn't exist: failure to STDERR
ls bozo

