#!/bin/sh

# To make custom error messages, we need this, not "set -e"
set -o errexit

# Log "exit 3" output in "exit-3.log"
exec 3>> exit-3.log

# Create a message upon "exit 3" ( 3> )
echo "Hey there! I'm exiting THREE!" >&3

exit 3
