#!/bin/sh

# Make this script exit if something is wrong
set -e

# Log all STDERR error messages in "errors.log"
exec 2>> errors.log

# Run ls
ls

# Create a message for STDOUT if there are no errors and thus no early exit
echo "ls was successful"

# Run ls for a dir that doesn't exist so it will create an STDERR and exit
ls dumbo

# This message will not display because the script just exited from the "ls dumbo" error
echo "ls dumbo was successful"

