#!/bin/sh

# Make this script exit if there is an STDERR error message
set -e

# Log all normal STDOUT output in "normal.log"
exec 1>> normal.log

# Log all STDERR error messages in "error.log"
exec 2>> error.log

# Run ls
ls

# Create a message for STDOUT if there are no errors and thus no early exit
echo "ls was successful"

# Run ls for a dir that doesn't exist so it will create an STDERR and exit
ls bozo

# This message will not display because the script just exited from the "ls bozo" error
echo "ls bozo was successful"

