#!/bin/sh

# Make this script exit if there is an STDERR error message
set -e

# Log all normal STDOUT output in "all.log"
exec 1>> all.log

# Redirect all STDERR ( 2> ) to become STDOUT ( 1> )
exec 2>&1

# Run ls
ls

# Create a message for STDOUT if there are no errors and thus no early exit
echo "ls was successful"

# Run ls for a dir that doesn't exist so it will create an STDERR and exit
ls bozo

# This message will not display because the script just exited from the "ls bozo" error
echo "ls bozo was successful"
