#!/bin/sh

# Log all STDERR error messages in "error.log"
#exec 2> error.log  # Only one ">" would over-write the log file; we want to append the log file, so we use ">>"
exec 2>> error.log

# Run ls: success to STDOUT
ls

# Run ls for a dir that doesn't exist: failure to STDERR
ls bozo

