#!/bin/sh

# Log all normal STDOUT output in "all.log"
exec 1>> all.log

# Redirect all STDERR ( 2> ) to become STDOUT ( 1> )
exec 2>&1

# Run ls: success to STDOUT
ls

# Run ls for a dir that doesn't exist: failure to STDERR
ls bozo
