#!/bin/sh

INPTNAME=$1
DATENAME="$(date +%Y-%m-%d_%H-%M-%S)"
PWGNNAME="$(pwgen -1 9)"

touch ${INPTNAME}${DATENAME}_${PWGNNAME}

echo "The file \"${INPTNAME}${DATENAME}_${PWGNNAME}\" has been created."
