#!/bin/sh

inptName=$1
dateName="$(date +%Y-%m-%d_%H-%M-%S)"
pwgnName="$(pwgen -1 9)"

touch ${inptName}${dateName}_${pwgnName}

echo "The file \"${inptName}${dateName}_${pwgnName}\" has been created."
