#!/bin/sh

input1=$1
Opertr=$2
input2=$3

case $Opertr in

# + Plus
+)

 echo "$input1 + $input2 = $(expr $input1 + $input2)"

;;

# - Minus
-)

 echo "$input1 - $input2 = $(expr $input1 - $input2)"

;;

# \* Multiplied by
\*)

 echo "$input1 * $input2 = $(expr $input1 \* $input2)"

;;

# / Divided by
/)

 echo "$input1 / $input2 = $(expr $input1 / $input2)"

;;

# % Modulus (remainder after divided)
%)

 echo "$input1 % $input2 = $(expr $input1 % $input2)"

;;

esac
