#!/bin/sh

input1=$1
Opertr=$2
input2=$3

case $Opertr in

# + Plus
+)

expr $input1 + $input2

;;

# - Minus
-)

expr $input1 - $input2

;;

# \* Multiplied by
\*)

expr $input1 \* $input2

;;

# / Divided by
/)

expr $input1 / $input2

;;

# % Modulus (remainder after divided)
%)

expr $input1 % $input2

;;

esac
