#!/bin/bash

input1=$1
Opertr=$2
input2=$3

case $Opertr in

# = EQual to
eq)

 if (( "$input1" == "$input2" )); then
 echo "$input1 & $input2 are equal."
 else
 echo "$input1 & $input2 are not equal."
 fi

;;

# != Not Equal to
ne)

 if (( "$input1" != "$input2" )); then
 echo "$input1 & $input2 are not equal."
 else
 echo "$input1 & $input2 are equal."
 fi

;;

# > Greater Than
gt)

 if (( "$input1" > "$input2" )); then
 echo "$input1 is greater than $input2."
 else
 echo "$input1 is not greater than $input2."
 fi

;;

# < Less Than
lt)

 if (( "$input1" < "$input2" )); then
 echo "$input1 is less than $input2."
 else
 echo "$input1 is not less than $input2."
 fi

;;

# >= Greater than or Eauql to
ge)

 if (( "$input1" >= "$input2" )); then
 echo "$input1 is greater than or equal to $input2."
 else
 echo "$input1 is not greater than or equal to $input2."
 fi

;;

# <= Less than or Equal to
le)

 if (( "$input1" <= "$input2" )); then
 echo "$input1 is less than or equal to $input2."
 else
 echo "$input1 is not less than or equal to $input2."
 fi

;;

esac
