#!/bin/bash

INPT1=$1
INPT2=$2
OPERT=$3


case $OPERT in 

# = EQual to
eq)

 if (( "$INPT1" == "$INPT2" )); then
 echo "$INPT1 & $INPT2 are equal."
 else
 echo "$INPT1 & $INPT2 are not equal."
 fi

;;

# != Not Equal to
ne)

 if (( "$INPT1" != "$INPT2" )); then
 echo "$INPT1 & $INPT2 are not equal."
 else
 echo "$INPT1 & $INPT2 are equal."
 fi

;;

# > Greater Than
gt)

 if (( "$INPT1" > "$INPT2" )); then
 echo "$INPT1 is greater than $INPT2."
 else
 echo "$INPT1 is not greater than $INPT2."
 fi

;;

# < Less Than
lt)

 if (( "$INPT1" < "$INPT2" )); then
 echo "$INPT1 is less than $INPT2."
 else
 echo "$INPT1 is not less than $INPT2."
 fi

;;

# >= Greater than or Eauql to
ge)

 if (( "$INPT1" >= "$INPT2" )); then
 echo "$INPT1 is greater than or equal to $INPT2."
 else
 echo "$INPT1 is not greater than or equal to $INPT2."
 fi

;;

# <= Less than or Equal to
le)

 if (( "$INPT1" <= "$INPT2" )); then
 echo "$INPT1 is less than or equal to $INPT2."
 else
 echo "$INPT1 is not less than or equal to $INPT2."
 fi

;;

esac

