#!/bin/bash

Key1=$1
Key2=$2

declare -A myArray
myArray[i]=one
myArray[ii]=two
myArray[iii]=three
myArray[iv]=four
myArray[v]=five
echo ${myArray[$Key1]}

# Quit here if no second variable
if [ -z "$2" ]; then
exit 0; fi

myArray=([I]=ONE [II]=TWO [III]=THREE [IV]=FOUR [V]=FIVE)
echo ${myArray[$Key2]}
