#!/bin/bash

KEY1=$1
KEY2=$2

declare -A myArray
myArray[i]=one
myArray[ii]=two
myArray[iii]=three
myArray[iv]=four
myArray[v]=five
echo ${myArray[$KEY1]}

# Quit here if no second variable
if [ -z "$2" ]; then
exit 0; fi

declare -A myArrayWik
myArrayWik=([I]=ONE [II]=TWO [III]=THREE [IV]=FOUR [V]=FIVE)
echo ${myArrayWik[$KEY2]}
