#!/bin/bash

inputVariable="$1"
WORD=Variable # $WORD = "Variable", so "input$WORD" = "inputVariable"
scriptVariable="input$WORD" #so scriptVariable="inputVariable"

echo "$inputVariable		$scriptVariable		${!scriptVariable}"
