#!/bin/bash

inputVariable="$1"
WORD=Variable
scriptVariable="input${WORD}" #so scriptVariable="inputVariable"
# ${WORD} = "Variable", so "input${WORD}" = "inputVariable"

echo "$1		$scriptVariable		${!scriptVariable}"

