#!/bin/bash

select Input in Hi Yo-yo Quit; do

 if [ "$Input" = "Hi" ]; then
  echo "Hi back at ya!"

 elif [ "$Input" = "Yo-yo" ]; then
  echo "It goes up and down."

 elif [ "$Input" = "Quit" ]; then
  echo "Quitting."
  break

 else
  echo "Not an option. Try again."

 fi
done
