#!/bin/bash

# Evaluate proper flags
while getopts ":a:bcde:h" Flg; do
 case $Flg in
## Do nothing for valid flags
  abcde)
   :
  ;;

## Error for invalid flags
  \?)
   echo "You used an invalid flag: -${OPTARG}" >&2
   echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
   exit 1
  ;;

## Help
  h)
   echo "You asked for help!"
   echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
   exit 0
  ;;
 esac
done

# Create $globalArg
eval "globalArg=\${${OPTIND}}"
# If no argument input
if [ -z "${globalArg}" ]; then
 echo "You didn't set any options!"
 echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
 exit 1
fi

# Set the OPTIND variable in case it is different
OPTIND=1

# Get and run the options
while getopts ":a:bcde:h" Flg; do
 case $Flg in

  a)
   echo "Work option A with $OPTARG"
  ;;

  b)
   echo "Work option B with $globalArg"
  ;;

  c)
   echo "Work option C with $globalArg"
  ;;

  d)
   echo "Work option D with $globalArg"
  ;;

  e)
   echo "Work option E with $OPTARG"
  ;;

  h)
   echo "You Asked for help!"
   echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
   exit 0
  ;;
## If a wrong option is input
  *)
   echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
   exit 1
  ;;

 esac
done

#Clear $OPTIND from this getopts() function, just in case it is used later in this script
shift "$((OPTIND-1))"
