#!/bin/bash

# Create a help or "How to use" message function
function how_to_use()
{
 echo " How to use:
 $0 [-a <option>] [-b <option>] [-c <option>] [-d <option>]
 $0 -h ...will show this message."
}

# Get and run the options
while getopts ":a:b:c:d:h" flg; do
 case $flg in

  a)
   echo "Work with $OPTARG"
  ;;

  b) 
   echo "Work with $OPTARG"
  ;;

  c)
   echo "Work with $OPTARG"
  ;;

  d)
   echo "Work with $OPTARG"
  ;;

# Call our "How to use" function
## If used the -h option
  h)
   echo "Great! You asked for help."
   how_to_use
   exit 0
  ;;

## If a wrong option is used
  *)
   echo "Wrong."
   how_to_use
   exit 1
  ;;

 esac
done
#Clear $OPTIND from this getopts() function, just in case it is used later in this script
shift "$((OPTIND-1))"
