#!/bin/bash

# Create a help or "How to use" message function
function how_to_use()
{
 echo " How to use:
 $0 -a <option> -b|c|d <option>
 $0 -h ...will show this message."
}

# Alternate way to evaluate if a wrong flag is used, run this do loop first
while getopts ":a:bcde:" flg; do
 case $flg in
## Do nothing for valid flags
  abcde)
   :
  ;;

## Error for invalid flags
  \?)
   echo "You used an invalid flag: -${OPTARG}" >&2
   how_to_use
   exit 1
  ;;

## Help
  h)
   echo "You asked for help!"
   how_to_use
   exit 0
  ;;
 esac
done

# Alternate way to evaluate if no option is used
eval "GLOBALARG=\${${OPTIND}}"
if [ -z "${GLOBALARG}" ]; then
 echo "You didn't set any options!"
 how_to_use
 exit 1
fi

# Set the OPTIND variable in case it is different 
OPTIND=1

# Get and run the options
while getopts ":a:bcde:h" flg; do
 case $flg in

  a)
   echo "Work option A with $OPTARG"
   ;;

  b)
   echo "Work option B with $GLOBALARG"
   ;;

  c)
   echo "Work option C with $GLOBALARG"
   ;;

  d)
   echo "Work option D with $GLOBALARG"
   ;;

  e)
   echo "Work option E with $OPTARG"
   ;;

  h)
   echo "You Asked for help!"
   how_to_use
   exit 0
  ;;
## If a wrong option is used
  *)
   how_to_use
   exit 1
  ;;

 esac
done

#Clear $OPTIND from this getopts() function, just in case it is used later in this script
shift "$((OPTIND-1))"

