#!/bin/bash

# Get and run the options
while getopts ":abcdh" Flg; do
 case $Flg in

  a)
   echo "Work option A with flag -$Flg"
  ;;

  b)
   echo "Work option B with flag -$Flg"
  ;;

  c)
   echo "Work option C with flag -$Flg"
  ;;

  d)
   echo "Work option D with $OPTARG and flag -$Flg"
  ;;

## Help
  h)
   echo "You asked for help!"
   echo " How to use:
 $0 -a|b|c|d <option>
 $0 -h ...will show this message."
   exit 0
  ;;

## If a wrong option is input
  *)
   echo "Wrong..."
   echo " How to use:
 $0 -a|b|c|d <option>
 $0 -h ...will show this message."
   exit 1
  ;;

 esac
done
