#!/bin/bash

# Create a help message function
function how_to_use()
{
 echo " How to use:
 $0 -a <option> -b <option>
 $0 -h ...will show this message."
}


# Get and run the options
while getopts ":a:b:h" flg; do
 case $flg in

  a)
   echo "Work with $OPTARG using flag -$flg"
  ;;

  b) 
   echo "Work with $OPTARG using flag -$flg"
  ;;

## Help
  h)
   echo "Great! You asked for help."
   how_to_use
   exit 0
  ;;

## If a wrong option is input
  *)
   echo "Wrong."
   how_to_use
   exit 1
  ;;

 esac
done

