#!/bin/bash

# Evaluate proper flags
while getopts ":abcdh" Flg; do
 case $Flg in
## Do nothing for valid flags
  abcd)
   :
  ;;

## Error for invalid flags
  \?)
   echo "You used an invalid flag: -${OPTARG}" >&2
   echo " How to use:
 $0 -a|b|c|d <option>
 $0 -h ...will show this message."
   exit 1
  ;;

## Help
  h)
   echo "You asked for help!"
   echo " How to use:
 $0 -a|b|c|d <option>
 $0 -h ...will show this message."
   exit 0
  ;;
 esac
done

# Create $globalArg
eval "globalArg=\${${OPTIND}}"
# If no argument input
if [ -z "${globalArg}" ]; then
 echo "You didn't set any options!"
 echo " How to use:
 $0 -a|b|c|d <option>
 $0 -h ...will show this message."
 exit 1
fi

# Set the OPTIND variable in case it is different
OPTIND=1

# Get and run the options
while getopts ":abcd" Flg; do
 case $Flg in

  a)
   echo "Work option A with $globalArg using flag -$Flg"
  ;;

  b)
   echo "Work option B with $globalArg using flag -$Flg"
  ;;

  c)
   echo "Work option C with $globalArg using flag -$Flg"
  ;;

  d)
   echo "Work option D with $globalArg using flag -$Flg"
  ;;

 esac
done

#Clear $OPTIND from this getopts() function, just in case it is used later in this script
shift "$((OPTIND-1))"
