#!/bin/bash

# Get and run the options
while getopts ":a:b:c:d:h" flg; do
 case $flg in

  a)
   echo "Work with $OPTARG using flag -$flg"
  ;;

  b) 
   echo "Work with $OPTARG using flag -$flg"
  ;;

  c)
   echo "Work with $OPTARG using flag -$flg"
  ;;

  d)
   echo "Work with $OPTARG using flag -$flg"
  ;;

## Help
  h)
   echo "Great! You asked for help."
   echo " How to use:
 $0 -a <option> -b <option> -c <option> -d <option>
 $0 -h ...will show this message."
   exit 0
  ;;

## If a wrong option is input
  *)
   echo "Wrong."
   echo " How to use:
 $0 -a <option> -b <option> -c <option> -d <option>
 $0 -h ...will show this message."
   exit 1
  ;;

 esac
done

