#!/bin/bash

# Create a help or "How to use" message function
function how_to_use()
{
 echo " How to use:
 $0 -a <option> -b|c|d|e
 $0 --alpha <option> --beetle --ecko
 $0 -h ...will show this message.
 -a --alpha
 -b --beetle
 -c --charlie
 -d --delta
 -e --ecko
 -h --help"
}

# If no options
## getopt already handles invalid options, so this is all we need
if [ -z $1 ]; then
 echo "You didn't set any options!"
 how_to_use
 exit 1
fi

# Set the options as a variable
myOptions=`getopt -o a:bcdeh -l alpha:,beetle,charlie,delta,ecko,help -n "$(basename "$0")" -- "$@"`
#Alternative way to do the same thing
#myOptions=$(getopt --options a:bcdeh --longoptions :alpha:,beetle,charlie,delta,ecko,help --name "$(basename "$0")" -- "$@")

# Run and check the options
eval set --"$myOptions"

# Set the OPTIND variable in case it is different 
OPTIND=1

# Set the variables to false
alpha=false
beetle=false
charlie=false
delta=false
ecko=false
helpme=false

# Get and run the options
## This evaluates if parameters are present: [[ $# -gt 0 ]]
while [[ $# > 0 ]]; do
 case $1 in

  -a | --alpha )
   alpha=true
   alphaOPTION="$2"
### shift 2 moves 2 variables over since one variable is the setting for option -a
   shift 2
   ;;

  -b | --beetle )
   beetle=true
### shift 1 only moves 1 variable over since these options don't have settings
   shift 1
   ;;

  -c | --charlie )
   charlie=true
   shift 1
   ;;

  -d | --delta )
   delta=true
   shift 1
   ;;

  -e | --ecko )
   ecko=true
   shift 1
   ;;

## Help
  -h | --help )
   echo "You asked for help!"
   how_to_use
   exit 0
  ;;

## Finally break the loop (this will run 'break' no matter what)
  *)
   break
  ;;

 esac
done

#Clear $OPTIND from this getopts() function, just in case it is used later in this script
shift "$((OPTIND-1))"

# Run the actions based on what was set above
## Help

## Normal options
if [ $alpha = true ]; then
   echo "Work option A with $alphaOPTION"
fi

if [ $beetle = true ]; then
   echo "Work option B"
fi

if [ $charlie = true ]; then
   echo "Work option C"
fi

if [ $delta = true ]; then
   echo "Work option D"
fi

if [ $ecko = true ]; then
   echo "Work option E"
fi

