#!/bin/sh

# Set the global variables outside the function
varGlobalOne=$1
varGlobalTwo=$2

functionName() {

local varLocalOne=$1
local varLocalTwo=$2

echo "\"global\" variables used inside the function:

varGlobalOne = $varGlobalOne
varGlobalTwo = $varGlobalTwo

\"local\" variables used inside the function:

varLocalOne = $varLocalOne
varLocalTwo = $varLocalTwo
"

}

echo "First, run the function..."

functionName $varGlobalOne $varGlobalTwo

echo "\"global\" variables used outside the function:

varGlobalOne = $varGlobalOne
varGlobalTwo = $varGlobalTwo

\"local\" variables used outside the function:

varLocalOne = $varLocalOne
varLocalTwo = $varLocalTwo
"
